### ISSUE TITLE
Data Analysis Track

### ISSUE THREAD

**Issue by Mohamed3oraby** [Mohamed3oraby/treehouse#1]
## TODO

*Courses left to complete the Treehouse Data Analysis Track*

1. **A Number Guessing Game**
 
* [x] #3
* [x] #4
* [x] Share your Techdegree Projects on GitHub
* [x] Basic Math for Data Analysis 
* [x] Reusing Code on A Techdegree Project 
* [ ] A Number Guessing Game
