### ISSUE TITLE
Python Basics

### ISSUE THREAD

**Issue by Mohamed3oraby** [Mohamed3oraby/treehouse#2]
## TODO

**Python Basics Coursework**

* [x]  Meet Python 
* [x]  Types and Branching 
* [x]  Functions and Looping 
* [x]  All Together Now 

### Master Ticket app. 

- [x]  As a user, I should be showing the number of tickets left remaining so, I can understand the importance of buying now. 
- [x] As a user, I should have a personalized experience so that I feel welcome by the brand. 
- [x] As a user, I should have errors reported in a user friendly manner. 
- [x] As a user, I should be able to request a certain amount of tickets. 
- [x] As a user, I should be able to confirm my order so that I do not accidentally purchase more tickets than intended. 
- [x] As a user I should not be offered tickets if they're aren't any available.
- [x] As an owner I should receive a service charge so I can pay others to maintain this software.
