### ISSUE TITLE
Practice Python Basics

### ISSUE THREAD

**Issue by Mohamed3oraby** [Mohamed3oraby/treehouse#3]

**Comment by Mohamed3oraby** [comment]
# TODO :+1: 

- [x] Practice Input and Output in Python
- [x] Practice Comparisons in Python
- [x] Practice Python While Loops
- [x] Practice Creating and Using Functions in Python
