### ISSUE TITLE
Introducing Lists

### ISSUE THREAD

**Issue by Mohamed3oraby** [Mohamed3oraby/treehouse#4]
# TODO 

- [x]  Meet Lists 
- [x]  Using Lists 
- [x]  Build an Application

**Comment by Mohamed3oraby** [comment]
### Build an Application 

- [x] As a user, I should continually be prompted so that I can add a grocery item or view my list when I need to. 
- [x] As a user, I should be able to ask for help so that I can understand how to use the application. 
- [x] As a user, I should be able to add an item for the list. 
- [x] As a user upon adding an item to a list, I should know the total length of my list so I don't go buy.
- [x] As a user, I should be able to see the list at any time so that I can verify my order. 
- [x] As a user I should be able to state when I'm done so that I can print out the list in totality.
